"""Sweet-spot grid parameter sweep across BTC/ETH/XRP × 2y.

Wraps scripts/volume_farm_grid_backtest.py simulator (post-only grid market-maker
with reanchor + inventory cap + maker rebates + hard-stop) and runs a parameter
sweep to find sweet-spot defaults per symbol.

Sweep dimensions (XBTUSD inverse contract — matches live SHORT bots):
  grid_levels    : 30, 60, 90, 120
  order_size_usd : 300, 500, 1000
  inventory_cap  : 0.10, 0.20

That's 24 combos × 3 symbols = 72 runs (~13 min total).

Outputs:
  docs/RESEARCH_grid_sweet_spot_2026-05-17.md
  state/bot_brain_grid_config.json  — recommended params per symbol

Usage:
    python scripts/grid_sweet_spot_sweep.py
    python scripts/grid_sweet_spot_sweep.py --symbol BTCUSDT  # one symbol
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from itertools import product
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import volume_farm_grid_backtest as g  # type: ignore

DATA_DIR = ROOT / "backtests" / "frozen"
DOC_PATH = ROOT / "docs" / "RESEARCH_grid_sweet_spot_2026-05-17.md"
CONFIG_PATH = ROOT / "state" / "bot_brain_grid_config.json"

SYMBOLS = ["BTCUSDT", "ETHUSDT", "XRPUSDT"]

# Inventory cap is symbol-specific in native units, but we want EQUIVALENT
# notional across symbols for fair comparison. Sweep in USD equivalent, then
# divide by first-bar mid to get native units per symbol.
# Reference: 0.10 BTC @ $78k = $7800 / 0.20 BTC = $15,600
SWEEP = {
    "grid_levels":    [30, 60, 90, 120],
    "order_size_usd": [300, 500, 1000],
    "inventory_cap_usd": [7800, 15600],  # was [0.10, 0.20] in BTC, now $-equivalent
}


def load_symbol(symbol: str) -> pd.DataFrame:
    csv = DATA_DIR / f"{symbol}_1m_2y.csv"
    df = pd.read_csv(csv, usecols=["ts", "open", "high", "low", "close"])
    df["ts"] = pd.to_datetime(df["ts"], unit="ms", utc=True)
    return df


def run_sweep(symbol: str) -> list[dict]:
    print(f"\n=== {symbol} ===", flush=True)
    df = load_symbol(symbol)
    print(f"  loaded {len(df):,} bars  {df.ts.iloc[0]} → {df.ts.iloc[-1]}", flush=True)
    first_mid = float(df["close"].iloc[0])
    results = []
    combos = list(product(SWEEP["grid_levels"], SWEEP["order_size_usd"],
                          SWEEP["inventory_cap_usd"]))
    for i, (levels, size, cap_usd) in enumerate(combos, start=1):
        # Convert USD-equivalent cap to native units (e.g. for ETH: $7800 / $2300 = 3.39 ETH)
        cap_native = cap_usd / first_mid
        p = g.Params(
            contract="inverse",
            grid_range_pct=0.6,
            grid_levels=levels,
            order_size_usd=float(size),
            inventory_cap_btc=float(cap_native),  # variable name is BTC-named but means native
            reanchor_drift_pct=0.3,
            hard_stop_unrealized_usd=-2000.0,
        )
        r = g.run(df, p)
        row = {
            "symbol": symbol,
            "levels": levels, "size_usd": size,
            "inventory_cap_usd": cap_usd, "inventory_cap_native": round(cap_native, 4),
            "total_net_usd": round(r["total_net_usd"], 0),
            "avg_daily_net": round(r["avg_daily_net_usd"], 2),
            "avg_daily_vol": round(r["avg_daily_volume_usd"], 0),
            "max_dd_usd": round(r["max_drawdown_in_run_usd"], 0),
            "days_pos": r["days_pos_net"],
            "days_neg": r["days_neg_net"],
            "fills_total": int(r.get("days_df", pd.DataFrame({"fills": [0]}))["fills"].sum())
                if "days_df" in r else 0,
        }
        results.append(row)
        print(f"  [{i:>2}/{len(combos)}]  levels={levels:>3} size=${size:>4} "
              f"cap=${cap_usd}/{cap_native:.3f}native  "
              f"net=${row['total_net_usd']:>+9,.0f}  daily=${row['avg_daily_net']:>+7.1f}  "
              f"vol/day=${row['avg_daily_vol']:>10,.0f}  dd=${row['max_dd_usd']:>+8,.0f}",
              flush=True)
    return results


def pick_sweet_spot(rows: list[dict]) -> dict:
    """Sweet-spot = highest daily_net per unit of max_dd risk.
    Score: avg_daily_net / max(|max_dd_usd|, 100)."""
    best = None
    best_score = -float("inf")
    for r in rows:
        risk = max(abs(r["max_dd_usd"]), 100)
        score = r["avg_daily_net"] / risk * 1000  # scaled
        if score > best_score:
            best_score = score
            best = {**r, "score": round(score, 3)}
    return best or {}


def write_markdown(by_symbol: dict[str, list[dict]]) -> None:
    lines = [
        "# Grid Sweet-Spot Sweep — 2026-05-17",
        "",
        "Generated by `scripts/grid_sweet_spot_sweep.py` — wraps post-only grid "
        "market-maker simulator from `scripts/volume_farm_grid_backtest.py`.",
        "",
        "Sweep on 2y BTC/ETH/XRP × **XBTUSD inverse** contract (matches live SHORT bots T1/T2/T3/TB).",
        "Fixed defaults: `grid_range_pct=0.6%`, `reanchor_drift=0.3%`, `hard_stop=-$2000`.",
        "",
        "Score = `avg_daily_net / max(|max_dd|, 100) × 1000` — return-per-DD efficiency.",
        "",
    ]
    for sym, rows in by_symbol.items():
        sweet = pick_sweet_spot(rows)
        lines.append(f"## {sym}")
        lines.append("")
        lines.append("| levels | size $ | cap $ (native) | total net $ | avg daily $ | avg daily vol $ | max DD $ | +/- days |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for r in sorted(rows, key=lambda x: -x["avg_daily_net"]):
            mark = " ⭐" if (sweet and r["levels"] == sweet["levels"] and
                              r["size_usd"] == sweet["size_usd"] and
                              r.get("inventory_cap_usd") == sweet.get("inventory_cap_usd")) else ""
            cap_disp = f"${r.get('inventory_cap_usd', '?')} ({r.get('inventory_cap_native', '?')})"
            lines.append(
                f"| {r['levels']} | {r['size_usd']} | {cap_disp} | "
                f"{r['total_net_usd']:+,.0f} | {r['avg_daily_net']:+,.2f} | "
                f"{r['avg_daily_vol']:,.0f} | {r['max_dd_usd']:+,.0f} | "
                f"{r['days_pos']}/{r['days_neg']}{mark} |"
            )
        lines.append("")
        if sweet:
            lines.append(f"**Sweet-spot:** levels={sweet['levels']}, size=${sweet['size_usd']}, "
                          f"cap=${sweet.get('inventory_cap_usd', '?')} "
                          f"({sweet.get('inventory_cap_native', '?')} native)  →  "
                          f"daily ${sweet['avg_daily_net']:+.2f}, DD ${sweet['max_dd_usd']:+,.0f}, "
                          f"score {sweet['score']}")
        lines.append("")

    lines.append("## Применение")
    lines.append("")
    lines.append("Sweet-spot per symbol записан в `state/bot_brain_grid_config.json` — "
                  "используется как default при создании новых ботов или recenter "
                  "(будущий R4 live).")
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {DOC_PATH}")


def write_config(by_symbol: dict[str, list[dict]]) -> None:
    config = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": "scripts/grid_sweet_spot_sweep.py",
        "contract": "inverse",
        "by_symbol": {},
    }
    for sym, rows in by_symbol.items():
        sweet = pick_sweet_spot(rows)
        if sweet:
            config["by_symbol"][sym] = {
                "grid_levels": sweet["levels"],
                "order_size_usd": sweet["size_usd"],
                "inventory_cap_usd_equiv": sweet.get("inventory_cap_usd"),
                "inventory_cap_native": sweet.get("inventory_cap_native"),
                "expected_daily_net_usd": sweet["avg_daily_net"],
                "expected_max_dd_usd": sweet["max_dd_usd"],
                "score": sweet["score"],
            }
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {CONFIG_PATH}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--symbol", choices=SYMBOLS + ["all"], default="all")
    args = ap.parse_args()

    symbols = SYMBOLS if args.symbol == "all" else [args.symbol]
    by_symbol = {}
    for sym in symbols:
        by_symbol[sym] = run_sweep(sym)

    write_markdown(by_symbol)
    write_config(by_symbol)


if __name__ == "__main__":
    main()
